config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :wishlist_items, except: [:index]
  resources :wishlists, only: [:index, :show]
  resource :user_profiles, only: [:show, :edit, :update]
  devise_for :users
  root 'home#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :wishlist
  has_one :user_profile

  after_create :create_wishlist, :create_profile

  private

  def create_wishlist
    wishlist = Wishlist.new(user_id: id)
    wishlist.save
  end

  def create_profile
    profile = UserProfile.new(user_id: id)
    profile.save
  end
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  belongs_to :user
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  belongs_to :user
  has_many :wishlist_items

  def count
    wishlist_items.count
  end
end

app/models/wishlist_item.rb
class WishlistItem < ActiveRecord::Base
  belongs_to :wishlist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :authenticate_user!, :set_user

  private

  def set_user
    @user_profile = UserProfile.where(user_id: current_user.id)
  end
end

app/controllers/wishlist_items_controller.rb
class WishlistItemsController < ApplicationController
  before_action :set_wishlist_item, only: [:show, :edit, :update, :destroy]

  # GET /wishlist_items/1
  # GET /wishlist_items/1.json
  def show
  end

  # GET /wishlist_items/new
  def new
    @wishlist_item = WishlistItem.new(wishlist_id: params[:wishlist_id])
  end

  # GET /wishlist_items/1/edit
  def edit
  end

  # POST /wishlist_items
  # POST /wishlist_items.json
  def create
    @wishlist_item = WishlistItem.new(wishlist_item_params)

    respond_to do |format|
      if @wishlist_item.save
        format.html { redirect_to @wishlist_item, notice: 'Wishlist item was successfully created.' }
        format.json { render :show, status: :created, location: @wishlist_item }
      else
        format.html { render :new }
        format.json { render json: @wishlist_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wishlist_items/1
  # PATCH/PUT /wishlist_items/1.json
  def update
    respond_to do |format|
      if @wishlist_item.update(wishlist_item_params)
        format.html { redirect_to @wishlist_item, notice: 'Wishlist item was successfully updated.' }
        format.json { render :show, status: :ok, location: @wishlist_item }
      else
        format.html { render :edit }
        format.json { render json: @wishlist_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishlist_items/1
  # DELETE /wishlist_items/1.json
  def destroy
    @wishlist_item.destroy
    respond_to do |format|
      format.html { redirect_to wishlist_items_url, notice: 'Wishlist item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_wishlist_item
    @wishlist_item = WishlistItem.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def wishlist_item_params
    params.require(:wishlist_item).permit(:name, :link, :wishlist_id)
  end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_wishlist, only: [:show, :edit, :update, :destroy]

  # GET /wishlists
  # GET /wishlists.json
  def index
    @wishlists = Wishlist.all
  end

  # GET /wishlists/1
  # GET /wishlists/1.json
  def show
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_wishlist
    @wishlist = Wishlist.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def wishlist_params
    params.require(:wishlist).permit(:user_id, :count)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/helpers/wishlist_items_helper.rb
module WishlistItemsHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/home/index.haml
%html
  %h1 Home

  =link_to "Sign up", "users/sign_up" 
  =link_to "Sign in", new_user_session_path unless user_signed_in?
  =link_to "Sign out", destroy_user_session_path, method: :delete if user_signed_in?
  =link_to "Wishlists", "wishlists"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WishList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en" }
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag

  %body

    = yield

app/views/user_profiles/show.html.haml
%h1 User Profile

%row 
  User is 
  = @user_profile.first.first_name

app/views/wishlist_items/_form.html.haml
= form_for @wishlist_item do |f|
  - if @wishlist_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@wishlist_item.errors.count, "error")} prohibited this wishlist_item from being saved:"
      %ul
        - @wishlist_item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :link
    = f.text_field :link
  = f.hidden_field(:wishlist_id, value: @wishlist_item.wishlist_id)
  .actions 
    %button{type: 'submit', class: 'button'} Save

app/views/wishlist_items/edit.html.haml
%h1 Editing wishlist_item

= render 'form'

= link_to 'Show', @wishlist_item
\|
= link_to 'Back', wishlist_items_path

app/views/wishlist_items/new.html.haml
%h1 New wishlist_item

= render 'form'

= link_to 'Back', wishlist_path(id: @wishlist_item.wishlist_id)

app/views/wishlist_items/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @wishlist_item.name
%p
  %b Link:
  = @wishlist_item.link
%p
  %b Wishlist:
  = @wishlist_item.wishlist.id

= link_to 'Edit', edit_wishlist_item_path(@wishlist_item)
\|
= link_to 'Back', wishlist_items_path

app/views/wishlists/index.html.haml
%h1 Listing wishlists

%table
  %thead
    %tr
      %th User
      %th Count
      %th
      %th

  %tbody
    - @wishlists.each do |wishlist|
      %tr
        %td= wishlist.user.email
        %td= wishlist.count
        %td= link_to 'Show', wishlist
      -wishlist.wishlist_items.each do |item|
        %tr
          %td= item.name

app/views/wishlists/show.html.haml
%p#notice= notice

%p
  %b User:
  = @wishlist.user.id
%p
  %b Count:
  = @wishlist.count
  
%table
  %thead 
    %tr
      %th Items
      
  %tbody
    - @wishlist.wishlist_items.each do |item|
      %tr
        - if item.link.blank?
          %td= item.name
        - else
          %td= link_to(item.name, item.link)

%br
= link_to 'Back', wishlists_path
= link_to 'Add', new_wishlist_item_path(wishlist_id: @wishlist.id), class: 'button'